#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Pro
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Exam_database")]
	public partial class student_tableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertstudent_table(student_table instance);
    partial void Updatestudent_table(student_table instance);
    partial void Deletestudent_table(student_table instance);
    #endregion
		
		public student_tableDataContext() : 
				base(global::Exam_Pro.Properties.Settings.Default.Exam_databaseConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public student_tableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public student_tableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public student_tableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public student_tableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<student_table> student_tables
		{
			get
			{
				return this.GetTable<student_table>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student_table")]
	public partial class student_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _s_no;
		
		private string _s_name;
		
		private string _s_usn;
		
		private string _s_sem;
		
		private string _s_branch;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ons_noChanging(string value);
    partial void Ons_noChanged();
    partial void Ons_nameChanging(string value);
    partial void Ons_nameChanged();
    partial void Ons_usnChanging(string value);
    partial void Ons_usnChanged();
    partial void Ons_semChanging(string value);
    partial void Ons_semChanged();
    partial void Ons_branchChanging(string value);
    partial void Ons_branchChanged();
    #endregion
		
		public student_table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_no", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string s_no
		{
			get
			{
				return this._s_no;
			}
			set
			{
				if ((this._s_no != value))
				{
					this.Ons_noChanging(value);
					this.SendPropertyChanging();
					this._s_no = value;
					this.SendPropertyChanged("s_no");
					this.Ons_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string s_name
		{
			get
			{
				return this._s_name;
			}
			set
			{
				if ((this._s_name != value))
				{
					this.Ons_nameChanging(value);
					this.SendPropertyChanging();
					this._s_name = value;
					this.SendPropertyChanged("s_name");
					this.Ons_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_usn", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string s_usn
		{
			get
			{
				return this._s_usn;
			}
			set
			{
				if ((this._s_usn != value))
				{
					this.Ons_usnChanging(value);
					this.SendPropertyChanging();
					this._s_usn = value;
					this.SendPropertyChanged("s_usn");
					this.Ons_usnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_sem", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string s_sem
		{
			get
			{
				return this._s_sem;
			}
			set
			{
				if ((this._s_sem != value))
				{
					this.Ons_semChanging(value);
					this.SendPropertyChanging();
					this._s_sem = value;
					this.SendPropertyChanged("s_sem");
					this.Ons_semChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_branch", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string s_branch
		{
			get
			{
				return this._s_branch;
			}
			set
			{
				if ((this._s_branch != value))
				{
					this.Ons_branchChanging(value);
					this.SendPropertyChanging();
					this._s_branch = value;
					this.SendPropertyChanged("s_branch");
					this.Ons_branchChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
