<?xml version="1.0" encoding="utf-8"?><Database Name="Exam_database" Class="student_tableDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-250RMIQ\SQLEXPRESS;Initial Catalog=Exam_database;Integrated Security=True" SettingsObjectName="Exam_Pro.Properties.Settings" SettingsPropertyName="Exam_databaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.student_table" Member="student_tables">
    <Type Name="student_table">
      <Column Name="s_no" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="s_name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="s_usn" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="s_sem" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="s_branch" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>